### ISSUE TITLE
How does the Among Us Protocol decide ports

### ISSUE THREAD

**Issue by DamonPalovaara** [codyphobe/among-us-protocol#11]
I was wondering if you had any information on how Among Us chooses ports and what information they send on each port.

**Comment by codyphobe** [comment]
The ports are determined by the matchmaking server when a player creates a game, and custom servers can use any port because of this. The only other port with different data is the announcement server port which is hardcoded to `22024`, but I haven't taken the time to write up the details on that yet. There is also a separate port for LAN games, which is `47777`, which passes the same data as online games.
